services:
  database:
    image: postgres:16
    container_name: face_reg_quiz
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - /home/docker-data/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8085:80"
    depends_on:
      - database

  redis:
      image: redis:7-alpine
      container_name: face_reg_redis
      restart: always
      ports:
        - "6379:6379"

  # app:
  #   build: .
  #   container_name: face_test_app
  #   environment:
  #     DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
  #   expose:
  #     - "8000"
  #   volumes:
  #     - ./app:/app/app
  #     - ./app/uploads:/app/app/uploads

  # gateway:
  #   image: nginx:alpine
  #   container_name: nginx_gateway
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - app
